FROM python:3.10-slim

RUN apt-get update

WORKDIR /dota2

COPY poetry.lock poetry.lock
COPY pyproject.toml pyproject.toml
RUN pip install poetry
RUN poetry install

COPY dota2_lobby /dota2

CMD ["python", "lobby.py"]